<a href="https://colab.research.google.com/github/DONGSANSUNJAE/project/blob/main/%EA%B4%80%EA%B4%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so
import missingno as msno
import os
plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False)
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import GradientBoostingRegressor
import re
from functools import reduce
from collections import defaultdict


%config InlineBackend.figure_format = 'retina'

In [ ]:
from google.colab import drive
# 구글 드라이브 마운트
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2023년 국민여행조사 원자료_국내여행.xlsx')

In [ ]:
df.head()

,아이디,공통] A_여행 횟수-1. 국내 관광/휴양 여행,공통] A_여행 횟수-2. 국내 가족/친지/친구 방문 여행 - 관광/휴양 활동 포함,공통] A_여행 횟수-3. 국내 단순 가족/친지/친구 방문 - 관광/휴양 활동이 포함되지 않음,공통] A_여행 횟수-4. 국내 출장/업무 여행 - 관광/휴양 활동 포함,공통] A_여행 횟수-5. 국내 단순 출장/업무 경험 - 관광/휴양 활동이 포함되지 않음,"공통] A_여행 횟수-6. 1년 이하 해외여행 경험 - 관광/휴양 활동, 가족/친지/친구 방문, 출장/업무 등 모두 포함",공통] A-1_여행경험_국내 가족/친지/친구 방문 여행-관광/휴양 활동,공통] A-2_여행경험_국내 가족/친지/친구 방문 여행-관광/휴양 활동 포함,공통] A-3_여행경험_국내 단순 가족/친지/친구 방문-관광/휴양 활동 포함되지 않음,...,국내] 분석변수_여행시기_기타전체여행_휴일,국내] 분석변수_여행시기_기타전체여행_명절연휴,국내] 분석변수_여행시기_기타숙박여행_평일,국내] 분석변수_여행시기_기타숙박여행_주말,국내] 분석변수_여행시기_기타숙박여행_휴일,국내] 분석변수_여행시기_기타숙박여행_명절연휴,국내] 분석변수_여행시기_기타당일여행_평일,국내] 분석변수_여행시기_기타당일여행_주말,국내] 분석변수_여행시기_기타당일여행_휴일,국내] 분석변수_여행시기_기타당일여행_명절연휴
0,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,SA1_6,MON_EXP_1,MON_EXP_2,MON_EXP_3,...,국내_A_기타전체여행_휴일,국내_A_기타전체여행_명절연휴,국내_A_기타숙박여행_평일,국내_A_기타숙박여행_주말,국내_A_기타숙박여행_휴일,국내_A_기타숙박여행_명절연휴,국내_A_기타당일여행_평일,국내_A_기타당일여행_주말,국내_A_기타당일여행_휴일,국내_A_기타당일여행_명절연휴
1,11010560931_124820,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010560931_124821,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010560931_124823,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010560931_124825,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data = df # 원 데이터 보존을 위함

In [ ]:
data.columns = df.iloc[0]

data = data.drop(data.index[0])

data = data.reset_index(drop=True)

In [ ]:
data.head()

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,SA1_6,MON_EXP_1,MON_EXP_2,MON_EXP_3,...,국내_A_기타전체여행_휴일,국내_A_기타전체여행_명절연휴,국내_A_기타숙박여행_평일,국내_A_기타숙박여행_주말,국내_A_기타숙박여행_휴일,국내_A_기타숙박여행_명절연휴,국내_A_기타당일여행_평일,국내_A_기타당일여행_주말,국내_A_기타당일여행_휴일,국내_A_기타당일여행_명절연휴
0,11010560931_124820,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010560931_124821,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010560931_124823,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010560931_124825,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010560931_124833,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.tail()

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,SA1_6,MON_EXP_1,MON_EXP_2,MON_EXP_3,...,국내_A_기타전체여행_휴일,국내_A_기타전체여행_명절연휴,국내_A_기타숙박여행_평일,국내_A_기타숙박여행_주말,국내_A_기타숙박여행_휴일,국내_A_기타숙박여행_명절연휴,국내_A_기타당일여행_평일,국내_A_기타당일여행_주말,국내_A_기타당일여행_휴일,국내_A_기타당일여행_명절연휴
52106,39020620051_297295,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52107,39020620051_297296,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52108,39020620051_297297,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52109,39020620051_297298,0,0,0,1,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52110,39020620051_297299,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 데이터 정제

In [ ]:
delete_column = ['SDAY', 'EDAY']
data = data[[col for col in data.columns if not any(exclude in col for exclude in delete_column)]]

In [ ]:
delete_column_1 = [
    'A8_1', 'PA8_1', 'NA8_1', 'A8_2', 'PA8_2', 'NA8_2', 'A8_3', 'PA8_3', 'NA8_3',
    'A8_4', 'PA8_4', 'NA8_4', 'A8_5', 'PA8_5', 'NA8_5', 'A8_6', 'PA8_6', 'NA8_6',
    'A8_7', 'PA8_7', 'NA8_7', 'A8_8', 'PA8_8', 'NA8_8', 'A8_9', 'PA8_9', 'NA8_9',
    'A8_10', 'PA8_10', 'NA8_10', 'A8_TOTAL', 'NA8_TOTAL', 'A9A', 'NA9A', 'A9A_1',
    'PA9A_1', 'NA9A_1', 'A9A_2', 'PA9A_2', 'NA9A_2', 'A9A_3', 'PA9A_3', 'NA9A_3',
    'A9B', 'PA9B', 'NA9B', 'A9C', 'NA9C', 'A9C_1', 'PA9C_1', 'NA9C_1', 'A9C_2',
    'PA9C_2', 'NA9C_2', 'A9C_3', 'PA9C_3', 'NA9C_3', 'A9C_4', 'PA9C_4', 'NA9C_4',
    'A9C_5', 'PA9C_5', 'NA9C_5', 'A9C_6', 'PA9C_6', 'NA9C_6', 'A9C_7', 'PA9C_7',
    'NA9C_7', 'A9C_8', 'PA9C_8', 'NA9C_8', 'A9C_9', 'PA9C_9', 'NA9C_9', 'A9C_10',
    'PA9C_10', 'NA9C_10', 'A9C_11', 'PA9C_11', 'NA9C_11', 'A9C_12', 'PA9C_12',
    'NA9C_12', 'A9C_13', 'PA9C_13', 'NA9C_13', 'A9C_14', 'PA9C_14', 'NA9C_14',
    'A9D', 'NA9D', 'A9D_1', 'PA9D_1', 'NA9D_1', 'A9D_2', 'PA9D_2', 'NA9D_2',
    'A9D_3', 'PA9D_3', 'NA9D_3', 'A9E', 'NA9E', 'A9E_1', 'PA9E_1', 'NA9E_1',
    'A9E_2', 'PA9E_2', 'NA9E_2', 'A9E_3', 'PA9E_3', 'NA9E_3', 'A9E_4', 'PA9E_4',
    'NA9E_4'
]

# 2차 정제(비용적인 부분)
data = data.drop(columns=delete_column_1)

In [ ]:
delete_column_2 = [
    'A9F', 'NA9F', 'A9F_1', 'PA9F_1', 'NA9F_1', 'A9F_2', 'PA9F_2', 'NA9F_2', 'A9F_3',
    'PA9F_3', 'NA9F_3', 'A9F_4', 'PA9F_4', 'NA9F_4', 'A9F_5', 'NA9F_5', 'A9FA_1',
    'PA9FA_1', 'NA9FA_1', 'A9FA_2', 'PA9FA_2', 'NA9FA_2', 'A9FA_3', 'PA9FA_3', 'NA9FA_3',
    'A9FA_4', 'PA9FA_4', 'NA9FA_4', 'A9F_6', 'PA9F_6', 'NA9F_6', 'A9G', 'NA9G', 'A9G_1',
    'PA9G_1', 'NA9G_1', 'A9G_2', 'PA9G_2', 'NA9G_2', 'A9G_3', 'PA9G_3', 'NA9G_3', 'A9G_4',
    'PA9G_4', 'NA9G_4', 'A9G_5', 'PA9G_5', 'NA9G_5', 'A9G_6', 'PA9G_6', 'NA9G_6', 'A9H',
    'NA9H', 'A9H_1', 'PA9H_1', 'NA9H_1', 'A9H_2', 'PA9H_2', 'NA9H_2', 'A9H_3', 'PA9H_3',
    'NA9H_3', 'A9H_4', 'PA9H_4', 'NA9H_4', 'A9H_5', 'PA9H_5', 'NA9H_5', 'A9I', 'NA9I',
    'A9I_1', 'PA9I_1', 'NA9I_1', 'A9I_2', 'PA9I_2', 'NA9I_2', 'A9I_3', 'PA9I_3', 'NA9I_3',
    'A9J', 'NA9J', 'A9J_1', 'PA9J_1', 'NA9J_1', 'A9', 'NA9', 'A9SC_1', 'A9SC_2', 'A9SC_3',
    'A9SC_4', 'A9SC_5', 'A9SC_6', 'A9SC_7', 'A9SD_1', 'A9SD_2', 'A9SD_3', 'A9SD_4', 'A9SD_5',
    'A9SD_6', 'A9SE_1', 'A9SE_2', 'A9SE_3', 'A9SF_1', 'A9SF_2', 'A9SF_3', 'A9SF_4'
]

# 3차 정제(비용적인 부분)
data = data.drop(columns=delete_column_2)

In [ ]:
delete_column_3 = [
    'D1_1', 'PD1_1', 'ND1_1', 'D1_2', 'PD1_2', 'ND1_2', 'D1_3', 'PD1_3', 'ND1_3',
    'D1_4', 'PD1_4', 'ND1_4', 'D1_5', 'PD1_5', 'ND1_5', 'D1_6', 'PD1_6', 'ND1_6',
    'D1_7', 'PD1_7', 'ND1_7', 'D1_8', 'PD1_8', 'ND1_8', 'D1_9', 'PD1_9', 'ND1_9',
    'D_TOTAL', 'ND_TOTAL'
]

# 4차 정제(비용적인 부분)
data = data.drop(columns=delete_column_3)

In [ ]:
delete_column_4 = ['여행지출']

# 5차 정제(비용적인 부분)
data = data[[col for col in data.columns if not any(exclude in col for exclude in delete_column_4)]]

In [ ]:
# 모든 열이 결측인 행을 찾고자 함
all_missing_rows = data[data.isnull().all(axis=1)]
if not all_missing_rows.empty:
    print("모든 열이 결측인 행 존재")
else:
    print("모든 열이 결측인 행이 존재X")

print(all_missing_rows)

모든 열이 결측인 행이 존재X
Empty DataFrame
Columns: [ID, SA1_1, SA1_2, SA1_3, SA1_4, SA1_5, SA1_6, MON_EXP_1, MON_EXP_2, MON_EXP_3, MON_EXP_4, MON_EXP_5, MON_EXP_6, D_TRA1_CHECK, D_TRA1_CASE, D_TRA1_SYEAR, D_TRA1_SMONTH, D_TRA1_EYEAR, D_TRA1_EMONTH, D_TRA1_S_Day, D_TRA1_COST, D_TRA1_NUM, D_TRA1_ONE_COST, D_TRA1_VAC, D_TRA1_1_SYEAR, D_TRA1_1_SMONTH, D_TRA1_1_EYEAR, D_TRA1_1_EMONTH, D_TRA1_1_SPOT, D_TRA1_1_Q6_Ar, D_TRA1_1_Q6, D_TRA1_2_SYEAR, D_TRA1_2_SMONTH, D_TRA1_2_EYEAR, D_TRA1_2_EMONTH, D_TRA1_2_SPOT, D_TRA1_2_Q6_Ar, D_TRA1_2_Q6, D_TRA1_3_SYEAR, D_TRA1_3_SMONTH, D_TRA1_3_EYEAR, D_TRA1_3_EMONTH, D_TRA1_3_SPOT, D_TRA1_3_Q6_Ar, D_TRA1_3_Q6, D_TRA1_4_SYEAR, D_TRA1_4_SMONTH, D_TRA1_4_EYEAR, D_TRA1_4_EMONTH, D_TRA1_4_SPOT, D_TRA1_4_Q6_Ar, D_TRA1_4_Q6, D_TRA1_5_SYEAR, D_TRA1_5_SMONTH, D_TRA1_5_EYEAR, D_TRA1_5_EMONTH, D_TRA1_5_SPOT, D_TRA1_5_Q6_Ar, D_TRA1_5_Q6, D_TRA1_6_SYEAR, D_TRA1_6_SMONTH, D_TRA1_6_EYEAR, D_TRA1_6_EMONTH, D_TRA1_6_SPOT, D_TRA1_6_Q6_Ar, D_TRA1_6_Q6, D_TRA1_7_SYEAR, D_TRA1_7_SMONTH, D_TRA1_7_EYEAR, D_TRA1_7_EMONTH, D_TRA1_7_SPOT, D_TRA1_7_Q6_Ar, D_TRA1_7_Q6, D_TRA1_8_SYEAR, D_TRA1_8_SMONTH, D_TRA1_8_EYEAR, D_TRA1_8_EMONTH, D_TRA1_8_SPOT, D_TRA1_8_Q6_Ar, D_TRA1_8_Q6, D_TRA1_9_SYEAR, D_TRA1_9_SMONTH, D_TRA1_9_EYEAR, D_TRA1_9_EMONTH, D_TRA1_9_SPOT, D_TRA1_9_Q6_Ar, D_TRA1_9_Q6, D_TRA1_10_SYEAR, D_TRA1_10_SMONTH, D_TRA1_10_EYEAR, D_TRA1_10_EMONTH, D_TRA1_10_SPOT, D_TRA1_10_Q6_Ar, D_TRA1_10_Q6, D_TRA1_11_SYEAR, D_TRA1_11_SMONTH, D_TRA1_11_EYEAR, D_TRA1_11_EMONTH, D_TRA1_11_SPOT, D_TRA1_11_Q6_Ar, ...]
Index: []

[0 rows x 1578 columns]

In [ ]:
os.getcwd()

'/content'

In [ ]:
data.to_csv('관광자료_1차정제.csv', index=False, encoding='utf-8-sig')

In [ ]:
data.head()

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,SA1_6,MON_EXP_1,MON_EXP_2,MON_EXP_3,...,국내_A_기타전체여행_휴일,국내_A_기타전체여행_명절연휴,국내_A_기타숙박여행_평일,국내_A_기타숙박여행_주말,국내_A_기타숙박여행_휴일,국내_A_기타숙박여행_명절연휴,국내_A_기타당일여행_평일,국내_A_기타당일여행_주말,국내_A_기타당일여행_휴일,국내_A_기타당일여행_명절연휴
0,11010560931_124820,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010560931_124821,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010560931_124823,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010560931_124825,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010560931_124833,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
check_columns = [col for col in data.columns if 'CHECK' in col]
data_check = data[check_columns]
data_check

,D_TRA1_CHECK,D_TRA2_CHECK,D_TRA3_CHECK,D_TRA4_CHECK,D_TRA5_CHECK,D_TRA6_CHECK
0,NaN,NaN,NaN,NaN,NaN,NaN
1,Y,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,Y,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
52106,NaN,NaN,NaN,NaN,NaN,NaN
52107,NaN,NaN,NaN,NaN,NaN,NaN
52108,Y,NaN,NaN,NaN,NaN,NaN
52109,Y,NaN,NaN,NaN,NaN,NaN
52110,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nan_rows = data_check.isna().all(axis=1)
nan_rows_count = nan_rows.sum()
nan_rows_count
# ??? 시발

27829

In [ ]:
second_column_name = data.columns[1]
thirteenth_column_name = data.columns[12]
print("2번째 열의 이름:", second_column_name)
print("13번째 열의 이름:", thirteenth_column_name)

subset_data = data.iloc[:, 1:13]
all_missing_rows = subset_data.isnull().all(axis=1)

# 모두 결측인 행이 있는지 확인
if all_missing_rows.any():
    print("있")
else:
    print("없")

2번째 열의 이름: SA1_1
13번째 열의 이름: MON_EXP_6
없

In [ ]:
condition = data['A1_1'].isnull() & (~data['A1_2'].isnull() | ~data['A1_3'].isnull())
rows_with_condition = data[condition]

# 조건 확인
if not rows_with_condition.empty:
    print("A1_1 열이 결측이지만 A1_2 또는 A1_3 열이 결측이 아닌 행이 있")
    print(rows_with_condition)
else:
    print("A1_1 열이 결측이지만 A1_2 또는 A1_3 열이 결측이 아닌 행이 없")

A1_1 열이 결측이지만 A1_2 또는 A1_3 열이 결측이 아닌 행이 없

In [ ]:
delete_column_5 = ['A2BA_1', 'A2BA_2', 'A2BA_3', 'A2BA_4', 'A2BA_5', 'A3_1', 'A3_2', 'A3_3', 'A3_4',
                   'A3_5', 'A3_6', 'A3_7', 'A3_10', 'A3_11']

# 6차 정제
data = data.drop(columns=delete_column_5)

In [ ]:
delete_column_6 = ['A6_1', 'A6_2', 'A6_3', 'A6A_1', 'A6A_2', 'A6A_3',
                   'A7', 'A7A', 'A7B_1', 'A7B_2', 'A7B_3', 'A7B_4', 'A7B_5', 'A7B_6', 'A7B_7']

# 7차 정제
data = data.drop(columns=delete_column_6)

In [ ]:
data.head()

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,SA1_6,MON_EXP_1,MON_EXP_2,MON_EXP_3,...,국내_A_기타전체여행_휴일,국내_A_기타전체여행_명절연휴,국내_A_기타숙박여행_평일,국내_A_기타숙박여행_주말,국내_A_기타숙박여행_휴일,국내_A_기타숙박여행_명절연휴,국내_A_기타당일여행_평일,국내_A_기타당일여행_주말,국내_A_기타당일여행_휴일,국내_A_기타당일여행_명절연휴
0,11010560931_124820,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010560931_124821,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010560931_124823,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010560931_124825,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010560931_124833,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.to_csv('관광자료_2차정제.csv', index=False, encoding='utf-8-sig')

In [ ]:
if 'DQ1' in data.columns:
    column_index = data.columns.get_loc('DQ1')
    print(f"'DQ1' 열은 {column_index + 1}번째 열입니다.")

'DQ1' 열은 844번째 열입니다.

In [ ]:
if 'DQ1' in data.columns:
    column_index = data.columns.get_loc('DQ1')
    print(f"'DQ1' 열은 {column_index + 1}번째 열입니다.")

In [ ]:
if 'DQ8' in data.columns:
    column_index = data.columns.get_loc('DQ8')
    print(f"'DQ8' 열은 {column_index + 1}번째 열입니다.")

'DQ1' 열은 869번째 열입니다.

In [ ]:
# 8차 정제

start_col = 844
end_col = 869
delete_column_7 = data.columns[start_col - 1:end_col]
data.drop(columns=delete_column_7, inplace=True, errors='ignore')

In [ ]:
if 'BJOB' in data.columns:
    column_index = data.columns.get_loc('BJOB')
    print(f"'BJOB' 열은 {column_index + 1}번째 열입니다.")

In [ ]:
if '국내_숙박여부' in data.columns:
    column_index = data.columns.get_loc('국내_숙박여부')
    print(f"'국내_숙박여부' 열은 {column_index + 1}번째 열입니다.")

In [ ]:
# 9차 정제

start_col_1 = 847
end_col_1 = 857
delete_column_8 = data.columns[start_col_1 - 1:end_col_1]
data.drop(columns=delete_column_8, inplace=True, errors='ignore')

In [ ]:
data.shape

(52111, 1512)

In [ ]:
# 10차 정제
delete_column_9 = ['여행횟수', '여행일수']
data = data[[col for col in data.columns if not any(exclude in col for exclude in delete_column_9)]]

In [ ]:
data.head()

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,SA1_6,MON_EXP_1,MON_EXP_2,MON_EXP_3,...,국내_A_기타전체여행_휴일,국내_A_기타전체여행_명절연휴,국내_A_기타숙박여행_평일,국내_A_기타숙박여행_주말,국내_A_기타숙박여행_휴일,국내_A_기타숙박여행_명절연휴,국내_A_기타당일여행_평일,국내_A_기타당일여행_주말,국내_A_기타당일여행_휴일,국내_A_기타당일여행_명절연휴
0,11010560931_124820,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010560931_124821,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010560931_124823,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010560931_124825,0,0,0,0,0,0,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010560931_124833,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.to_csv('관광자료_3차정제.csv', index=False, encoding='utf-8-sig')

NameError: name 'data' is not defined